// <auto-generated />
using System;
using IFSWebII.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IFSWebII.Migrations
{
    [DbContext(typeof(IFSDbContext))]
    partial class IFSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IFSWebII.Model.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Creditos")
                        .HasColumnType("int");

                    b.Property<double?>("Dificuldade")
                        .HasColumnType("float");

                    b.Property<string>("Ementa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HoraAula")
                        .HasColumnType("int");

                    b.Property<int?>("HoraRelogio")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Periodo")
                        .HasColumnType("int");

                    b.Property<int?>("QtdPratica")
                        .HasColumnType("int");

                    b.Property<int?>("QtdTeorica")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("IFSWebII.Model.Prerequisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Creditos")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int?>("NecessariaPara")
                        .HasColumnType("int");

                    b.Property<string>("NomeDisciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePrerequisito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Periodo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Prerequisitos");
                });

            modelBuilder.Entity("IFSWebII.Model.Prerequisito", b =>
                {
                    b.HasOne("IFSWebII.Model.Disciplina", null)
                        .WithMany("Prerequisitos")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IFSWebII.Model.Disciplina", b =>
                {
                    b.Navigation("Prerequisitos");
                });
#pragma warning restore 612, 618
        }
    }
}
